config/routes.rb
Rails.application.routes.draw do
  resources :contracts
  resources :tools

  resources :users do 
  	resources :tools
  	resources :contracts
  end

  resources :tools do
    resources :contracts
  end

  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  patch '/users/:id/contracts/:id/update', to: 'contracts#update'

  get    '/signup',  to: 'users#new'

  get 		'/login',  to: 'sessions#new'
  post 		'/login',  to: 'sessions#create'
  delete 	'/logout', to: 'sessions#destroy'

  get 'auth/facebook/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#new'

  root 'sessions#new'
end

app/models/tool.rb
class Tool < ApplicationRecord
	belongs_to :user
	has_many   :contracts

	def active
		if self.contracts.any? { |c| c.active}
			true
		else
			false
		end
	end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
		# add before: helper method to redirect if !logged_in?


	def index

		if params[:user_id]
			@user = User.find_by(id: params[:user_id])

			@tools = @user.tools
		
			respond_to do |format|
				format.html { render :index }
				format.json { render json: @tools }
			end
		else
			@user = current_user
		end
	end

	def new
		@tool = Tool.new
	end

	def create
		if logged_in?
			@tool = Tool.new(tool_params)
			@tool.user_id = current_user.id
			@user = current_user

			if @tool.valid?
				@tool.save
				respond_to do |format|
					format.html { redirect_to user_path(current_user.id), turbolinks: false}
					format.json { render json: @tool }
				end
			end
		else
			# add error message
			redirect_to user_path(current_user.id)
		end
	end

	def show
		if logged_in?
			@tool = Tool.find_by(id: params[:id])
			# binding.pry
				respond_to do |format|
					format.html { render :show }
					format.json { render json: @tool }
				end
		else
			redirect_to '/'
		end
	end

	def edit
		if logged_in?
			@tool = Tool.find_by(id: params[:id])
		else
			redirect_to '/'
		end
	end

	def update
    @tool = Tool.find_by_id(params[:id])
    @tool.update(tool_params)
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :edit
    end
  end

  def destroy

  	if logged_in?
  		@tool = Tool.find_by(id: params[:id])
  		if !@tool.active

		  	@tool = Tool.find_by(id: params[:id])
		  	@tool.destroy
		  	redirect_to user_tools_path(current_user)
		  elsif @tool.active
		  	# error message:  "So and so  is borrowing that tool right now!"
		  	redirect_to user_tools(current_user)
		  end
	  else
	  	redirect_to '/'
	  end
  end

  def new_tool
  	# renders new_tool form/partial 
  end

private
	def tool_params
		params.require(:tool).permit(:name, :description, :user_id, :active)
	end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_new_tool_form.html.erb
	<%= form_for @tool, :html => {:id => "create_tool", :data => {user_id: @user.id, turbolinks: false} } do |f|  %>
		<%= f.label :name, "Tool name: " %>
		<%= f.text_field :name %> <br>
		<%= f.label :description, "Description (optional): " %>	
		<%= f.text_field :description %>
		<%= f.submit "Create Tool", data: { disable_with: false }%>
	<% end %>

app/views/tools/edit.html.erb
<h1>Edit <%= @tool.name %></h1>

<%= form_for @tool do |f| %>
		<%= f.label :name, "Name: " %>
		<%= f.text_field :name %> <br>
		<%= f.label :description, "Description (optional): " %>
		<%= f.text_field :description %> <br>
		<%= f.submit "Update Tool" %>
	
	<% end %>


<%= button_to "Delete this Tool", tool_path(@tool), :method => :delete, data: { confirm: 'Are you sure?' } %>

app/views/tools/index.html.erb
<h2><%= @user.username%>'s Toolbox</h2>

<% @user.tools.each do |t| %>
	<p><b><%= t.name %>: </b> <%= t.description %></p>
	<p>
		<%= link_to "Edit Tool", edit_tool_path(t)%>
		<%= link_to "Delete Tool", tool_path(t), :method => :delete %>
	</p>
<% end %>
<p><%= link_to "Back to My Dashboard", user_path(@user) %></p>

app/views/tools/show.html.erb
<h2><%= @tool.name %></h2>
<h4>Description</h4>
<p><%= @tool.description %></p>

<%= link_to "Click here to Loan it out!", new_tool_contract_path(@tool) %>

<br>
<br>

	<% if !@tool.contracts.empty? %>
		<li>You have loaned this tool <%= @tool.contracts.length %> times!
		</li><br>
		<h4>Loan History</h4>
		<% @tool.contracts.each do |c| %>
			<ol>
				<li>Loaned to <%= c.borrower.username %> on <%= c.created_at.strftime("%a %b %d %Y") %></li>
			</ol>
			<% end %>
	<% else %>
		<p>You have not loaned this tool out yet.</p>
	<% end %>
<br>
<br>
<%= link_to "Click here to Edit or Delete Tool", edit_tool_path(@tool) %>
<p><%= link_to "Back to My Dashboard", user_path(@user)%></p>



<!-- add "loan it out" functionality... button that takes user to (tools/7/contracts/new) , and there, select user to loan it out to -->